# Generated by Django 5.1.1 on 2024-11-09 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("date_naissance", models.DateField(null=True)),
                ("date_mort", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lecteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("mdp", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Serie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=100)),
                ("nsfw", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Livre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("date_sortie", models.DateField()),
                ("nombre_pages", models.IntegerField()),
                ("auteurs", models.ManyToManyField(to="api.auteur")),
                (
                    "serie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.serie"
                    ),
                ),
                ("tags", models.ManyToManyField(to="api.tag")),
            ],
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("statut", models.CharField(max_length=20)),
                (
                    "lecteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.lecteur"
                    ),
                ),
                (
                    "livre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.livre"
                    ),
                ),
            ],
        ),
    ]
